version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - ./back/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - ./back/.env
    depends_on:
      - database
    ports:
      - "3001:3001"
    networks:
      - app-net

  postgres_emprestimos:
    image: postgres:16
    container_name: postgres-emprestimos
    env_file:
      - ./Microservicos/emprestimos/.env
    ports:
      - "5433:5432"
    volumes:
      - pg_data_emprestimos:/var/lib/postgresql/data
    networks:
      - app-net

  postgres_notificacoes:
    image: postgres:16
    container_name: postgres-notificacoes
    env_file:
      - ./Microservicos/notification/.env
    ports:
      - "5434:5432"
    volumes:
      - pg_data_notificacoes:/var/lib/postgresql/data
    networks:
      - app-net

  emprestimos:
    build:
      context: ./Microservicos/emprestimos
      dockerfile: Dockerfile
    container_name: emprestimos-service
    env_file:
      - ./Microservicos/emprestimos/.env
    depends_on:
      - postgres_emprestimos
    ports:
      - "3002:3002"
    networks:
      - app-net

  notification:
    build:
      context: ./Microservicos/notification
      dockerfile: Dockerfile
    container_name: notification-service
    env_file:
      - ./Microservicos/notification/.env
    depends_on:
      - postgres_notificacoes
    ports:
      - "3005:3005"
    networks:
      - app-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - backend
      - emprestimos
      - notification
    networks:
      - app-net

volumes:
  db_data:
  pg_data_emprestimos:
  pg_data_notificacoes:

networks:
  app-net:
    driver: bridge
