version: "3.9"

services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    environment:
      PORT: 3001
      DB_HOST: database
      DB_USER: app
      DB_PASSWORD: 123456
      DB_NAME: biblioteca
      TIMEZONE: America/Sao_Paulo
    restart: unless-stopped
    depends_on:
      - database
    command: ["sh", "./wait-for-db.sh", "database", "npm run dev"]
    ports:
      - "3001:3001"
    networks:
      - app-net

  postgres_emprestimos:
    image: postgres:16
    container_name: postgres-emprestimos
    environment:
      POSTGRES_USER: emprestimos
      POSTGRES_PASSWORD: emprestimos_pass
      POSTGRES_DB: emprestimos_db
      TZ: "America/Sao_Paulo"
    ports:
      - "5433:5432"
    volumes:
      - pg_data_emprestimos:/var/lib/postgresql/data
    networks:
      - app-net

  postgres_notificacoes:
    image: postgres:16
    container_name: postgres-notificacoes
    environment:
      POSTGRES_USER: notificacoes
      POSTGRES_PASSWORD: notificacoes_pass
      POSTGRES_DB: notificacoes_db
      TZ: "America/Sao_Paulo"
    ports:
      - "5434:5432"
    volumes:
      - pg_data_notificacoes:/var/lib/postgresql/data
    networks:
      - app-net

  emprestimos:
    build:
      context: ./Microservicos/emprestimos
      dockerfile: Dockerfile
    container_name: emprestimos-service
    environment:
      PORT: 3002
      BACKEND: http://backend:3001
      DB_HOST: postgres_emprestimos
      DB_USER: emprestimos
      DB_PASSWORD: emprestimos_pass
      DB_NAME: emprestimos_db
    depends_on:
      - postgres_emprestimos
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - app-net

  notification:
    build:
      context: ./Microservicos/notification
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      PORT: 3005
      DB_HOST: postgres_notificacoes
      DB_USER: notificacoes
      DB_PASSWORD: notificacoes_pass
      DB_NAME: notificacoes_db
    depends_on:
      - postgres_notificacoes
    restart: unless-stopped
    ports:
      - "3005:3005"
    networks:
      - app-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-container
    ports:
      - "80:80"
    depends_on:
      - backend
      - emprestimos
      - notification
    networks:
      - app-net

volumes:
  db_data:
  pg_data_emprestimos:
  pg_data_notificacoes:

networks:
  app-net:
    driver: bridge
