events {}

http {
    server {
        listen 80;
        server_name localhost;

        # Backend principal
        location /backend/ {
            proxy_pass http://backend:3001/;
        }

        # Microserviço de empréstimos
        location /emprestimos/ {
            proxy_pass http://emprestimos:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /notification/ {
            proxy_pass http://notification:3005/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
